version: '3.7'
services:  

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - mongodata:/data/db
    
volumes:
  mongodata: